name: dio_flow
description: A powerful and flexible HTTP client for Flutter applications, built on top of Dio with advanced features like mock support, GraphQL operations, file handling, caching, and automatic token management.
version: 1.3.0
homepage: https://github.com/Moein-dev/dio_flow
repository: https://github.com/Moein-dev/dio_flow
issue_tracker: https://github.com/Moein-dev/dio_flow/issues
documentation: https://github.com/Moein-dev/dio_flow/blob/main/README.md
license: MIT

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  shared_preferences: ^2.5.2
  log_curl_request: ^0.0.5
  colorful_log_plus: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
